### ISSUE TITLE
How do you uninstall pbLua?

### ISSUE THREAD

**Issue by MisterXtreme** [7HAL32/pbLua#1]
I installed pbLua on my NXT, and decided I want to use a different firmware, how do I do that?

**Comment by lutzthies** [comment]
Hi, you can follow the same steps which were necessary to flash the pbLua firmware. During the process, simply replace the firmware file *pbLua.rfw* with the [official Lego NXT firmware (v1.31)](https://lc-www-live-s.legocdn.com/r/www/r/mindstorms/-/media/franchises/mindstorms%202014/downloads/firmware%20and%20software/nxt%20software/firmware131_download1.zip?l.r2=798380141).

**Comment by MisterXtreme** [comment]
The problem is the brick is not detected as something the NXT software can flash to, it gets detected as some sort of COM port, and I can't change the driver so that the NXT software sees it as an NXT.

**Comment by alejo-reyes** [comment]
hello, same issue as @MisterXtreme I'm on mac osx, MINDSTORM NXT software cannot locate NXT.

**Comment by MisterXtreme** [comment]
I totally forgot about this, never got my brick fixed, I was thinking maybe I should open a new issue, would you like to instead?

**Comment by lutzthies** [comment]
Hi @alejo-reyes and @MisterXtreme, have you tried putting the NXT brick into firmware reflash mode? [It's described here for instance.](http://www.legoengineering.com/clicking-brick-syndrome/)

**Comment by MisterXtreme** [comment]
So, I finally took a look at my brick again, and when I try using either the soft, or even hard reset button, I still get pbLua, do you know of anyone who ever tried/did revert to the stock firmware?

**Comment by MisterXtreme** [comment]
I followed [these](https://bricks.stackexchange.com/a/4330) instructions, and viola, I was able to reinstall the stock firmware!

**Comment by lutzthies** [comment]
Great, glad to hear that. I will put this information into a FAQ section in the README file. Thanks for letting me know. 👍
